---

- hosts: all
  roles:
    - ansible-consul
  vars:
    consul_arch: "amd64"
    consul_version: 1.10.1
    consul_is_ui: true
    consul_is_server: true
    consul_use_systemd: true
    consul_use_upstart: false
    consul_use_initd: false
    consul_retry_join: true
    consul_install_nginx: false
    consul_install_nginx_config: false
    consul_enable_nginx_config: false
    consul_bind_address: "0.0.0.0"
    consul_dynamic_bind: false
    consul_client_address: "0.0.0.0"
    consul_client_address_bind: true
    consul_url: "http://192.168.25.2:8888/static"